name: postgwas1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - aws-c-auth=0.9.0
  - numpy=1.23.5
  - plink
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - bedtools=2.31.1
  - bitarray=2.9.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - cramjam=2.8.3
  - et_xmlfile=2.0.0
  - fastparquet=2024.2.0
  - gflags=2.2.2
  - glog=0.7.1
  - h2=4.1.0
  - hpack=4.0.0
  - htslib=1.21
  - hyperframe=6.0.1
  - idna=3.10
  - joblib=1.4.2
  - krb5=1.21.3
  - libabseil=20250512.1
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libdeflate=1.20
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.5.2
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.25
  - libparquet=17.0.0
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.0
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libutf8proc=2.10.0
  - libxgboost=2.1.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - mdurl=0.1.2
  - ncurses=6.5
  - openpyxl=3.1.5
  - openssl=3.6.0
  - orc=2.1.3
  - packaging=25.0
  - pandas=2.0.3
  - patsy=0.5.6
  - platformdirs=4.3.6
  - pooch=1.8.2
  - py-xgboost=2.1.1
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pybedtools=0.10.0
  - pycparser=2.22
  - pyliftover=0.4.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytz=2024.2
  - re2=2025.11.05
  - readline=8.2
  - requests=2.32.3
  - rich-argparse=1.6.0
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - six=1.16.0
  - snappy=1.2.2
  - statsmodels=0.14.1
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.2.3
  - wheel=0.45.1
  - xgboost=2.1.1
  - xlrd=2.0.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - cython=0.29
  - pip:
      - attrs==25.3.0
      - biopython==1.81
      - click==8.1.8
      - cloudpickle==3.1.2
      - dask==2023.5.0
      - fsspec==2025.3.0
      - importlib-metadata==8.5.0
      - locket==1.0.0
      - marshmallow==2.18.1
      - more-itertools==10.5.0
      - partd==1.4.1
      - pip==25.0.1
      - pluggy==0.13.1
      - psutil==7.1.3
      - py==1.11.0
      - pygments==2.19.2
      - pysam==0.23.3
      - pytest==5.3.5
      - pyyaml==6.0.3
      - rich==14.2.0
      - setuptools==59.8.0
      - toolz==1.0.0
      - wcwidth==0.2.14
      - zipp==3.20.2
      - polars-lts-cpu==0.20.31
      - git+https://github.com/bioinformed/vgraph.git
prefix: /Users/JJOHN41/miniconda3/envs/postgwas
